# Change these first
owner: muesliswap # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Main Website
    url: https://www.muesliswap.com
  - name: API Backend
    url: https://api.muesliswap.com/list?base-policy-id=&base-tokenname=


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.muesliswap.com
  # baseUrl: /your-repo-name
  logoUrl: https://muesliswap.com/logo512.png
  name: Upptime
  introTitle: "**Muesliswap** Status"
  introMessage: Real time status page of the Muesliswap website and its services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
