# Change these first
owner: MuesliSwapLabs # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Main Website
    url: https://www.muesliswap.com/health.html
    assignees:
      - TrimVis
      - chris-r-99
  - name: API Backend
    url: https://api.muesliswap.com/health
    assignees:
      - TrimVis
      - nielstron
  - name: Staking Backend
    url: https://staking.muesliswap.com/health
    assignees:
      - TrimVis
      - pcjordan
  - name: Tokens Backend
    url: https://tokens.muesliswap.com/health
    assignees:
      - TrimVis
      - nielstron
  - name: Onchain Backend
    url: https://onchain.muesliswap.com/health
    assignees:
      - TrimVis
      - nielstron

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.muesliswap.com 
  theme: night
  # baseUrl: /your-repo-name
  logoUrl: https://static.muesliswap.com/images/LogoIconLight.svg
  favicon: https://muesliswap.com/favicon.ico
  name: Muesliswap Status
  introTitle: "**Muesliswap** Status Page"
  introMessage: Real time status page of the Muesliswap website and its services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
